services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: express_super
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: express_test
    command: ["-c", "superuser_reserved_connections=10"]
    volumes:
      - ~/Desktop/pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  server:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      PORT: 3000
      NODE_ENV: production
      NODE_TYPE: development
      DB_PORT: 5432
      DB_HOST: db
      DB_USER: express_super
      DB_NAME: express_test
      DB_USER_PASS: admin
      JWT_SECRET: djasiudhausj
      EXPIRE_TIME: 3600
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ~/Desktop/logs:/usr/src/app/apps/be/logs
